In [2]:
import pandas as pd

# Change this to your actual CSV filename/path.
CSV_PATH = "./debug/track_matches.csv"

df = pd.read_csv(CSV_PATH)
print(f"Rows loaded: {len(df)}")
display(df.head())

Rows loaded: 206

,image_id,time,track_id,lat,lon,pixel_x,pixel_y,box_left,box_top,box_right,box_bottom
0,img_003839,13:25:00,T0047,39.937208,32.848238,183,408,163,388,202,427
1,img_003839,13:25:00,T0115,39.937401,32.849032,617,270,597,250,636,289
2,img_003839,13:25:00,T0182,39.937371,32.848247,188,292,168,272,207,311
3,img_003839,13:25:00,T0183,39.937246,32.849381,808,381,788,361,827,400
4,img_000926,11:35:00,T0154,39.931393,32.867863,821,17,801,0,840,36

In [3]:
# Count how many times every track_id occurs.
track_counts = df["track_id"].value_counts()

# Keep only track IDs that occur at least twice.
duplicates = track_counts[track_counts > 1]

print(f"Unique track IDs: {df['track_id'].nunique()}")
print(f"Track IDs occurring more than once: {len(duplicates)}")

if duplicates.empty:
    print("No duplicated TXXXX values found.")
else:
    display(duplicates.rename("count").to_frame())

Unique track IDs: 206
Track IDs occurring more than once: 0
No duplicated TXXXX values found.

In [4]:
# Show every row belonging to a duplicated track_id.
duplicate_rows = (
    df[df["track_id"].isin(duplicates.index)]
    .sort_values(["track_id", "time", "image_id"])
)

display(duplicate_rows)

Empty DataFrame
Columns: [image_id, time, track_id, lat, lon, pixel_x, pixel_y, box_left, box_top, box_right, box_bottom]
Index: []

In [5]:
# Optional: print a compact text summary.
for track_id, count in duplicates.items():
    image_ids = df.loc[df["track_id"] == track_id, "image_id"].tolist()
    print(f"{track_id}: {count} occurrences -> {image_ids}")

In [6]:
from pathlib import Path
import re

TRACK_SUMMARIES_DIR = Path("track_summaries")

# Match files like T0001.json, T0047.json, etc.
pattern = re.compile(r"^T\d{4}\.json$")

track_summary_files = [
    p for p in TRACK_SUMMARIES_DIR.iterdir()
    if p.is_file() and pattern.match(p.name)
]

print(f"TXXXX.json files in /track_summaries/: {len(track_summary_files)}")

TXXXX.json files in /track_summaries/: 226

In [7]:
track_ids_with_summary = sorted(p.stem for p in track_summary_files)

print(track_ids_with_summary)

['T0001', 'T0002', 'T0003', 'T0004', 'T0005', 'T0006', 'T0007', 'T0008', 'T0009', 'T0010', 'T0011', 'T0012', 'T0013', 'T0014', 'T0015', 'T0016', 'T0017', 'T0018', 'T0019', 'T0020', 'T0021', 'T0022', 'T0023', 'T0024', 'T0025', 'T0026', 'T0027', 'T0028', 'T0029', 'T0030', 'T0031', 'T0032', 'T0033', 'T0034', 'T0035', 'T0036', 'T0037', 'T0038', 'T0039', 'T0040', 'T0041', 'T0042', 'T0043', 'T0044', 'T0045', 'T0046', 'T0047', 'T0048', 'T0049', 'T0050', 'T0051', 'T0052', 'T0053', 'T0054', 'T0055', 'T0056', 'T0057', 'T0058', 'T0059', 'T0060', 'T0061', 'T0062', 'T0063', 'T0064', 'T0065', 'T0066', 'T0067', 'T0068', 'T0069', 'T0070', 'T0071', 'T0072', 'T0073', 'T0074', 'T0075', 'T0076', 'T0077', 'T0078', 'T0079', 'T0080', 'T0081', 'T0082', 'T0083', 'T0084', 'T0085', 'T0086', 'T0087', 'T0088', 'T0089', 'T0090', 'T0091', 'T0092', 'T0093', 'T0094', 'T0095', 'T0096', 'T0097', 'T0098', 'T0099', 'T0100', 'T0101', 'T0102', 'T0103', 'T0104', 'T0105', 'T0106', 'T0107', 'T0108', 'T0109', 'T0110', 'T0111', 'T0112', 'T0113', 'T0114', 'T0115', 'T0116', 'T0117', 'T0118', 'T0119', 'T0120', 'T0121', 'T0122', 'T0123', 'T0124', 'T0125', 'T0126', 'T0127', 'T0128', 'T0129', 'T0130', 'T0131', 'T0132', 'T0133', 'T0134', 'T0135', 'T0136', 'T0137', 'T0138', 'T0139', 'T0140', 'T0141', 'T0142', 'T0143', 'T0144', 'T0145', 'T0146', 'T0147', 'T0148', 'T0149', 'T0150', 'T0151', 'T0152', 'T0153', 'T0154', 'T0155', 'T0156', 'T0157', 'T0158', 'T0159', 'T0160', 'T0161', 'T0162', 'T0163', 'T0164', 'T0165', 'T0166', 'T0167', 'T0168', 'T0169', 'T0170', 'T0171', 'T0172', 'T0173', 'T0174', 'T0175', 'T0176', 'T0177', 'T0178', 'T0179', 'T0180', 'T0181', 'T0182', 'T0183', 'T0184', 'T0185', 'T0186', 'T0187', 'T0188', 'T0189', 'T0190', 'T0191', 'T0192', 'T0193', 'T0194', 'T0195', 'T0196', 'T0197', 'T0198', 'T0199', 'T0200', 'T0201', 'T0202', 'T0203', 'T0204', 'T0205', 'T0206', 'T0207', 'T0208', 'T0209', 'T0210', 'T0211', 'T0212', 'T0213', 'T0214', 'T0215', 'T0216', 'T0217', 'T0218', 'T0219', 'T0220', 'T0221', 'T0222', 'T0223', 'T0224', 'T0225', 'T0226']

In [8]:
print(f"Unique TXXXX in CSV: {df['track_id'].nunique()}")
print(f"TXXXX.json files:     {len(track_summary_files)}")

Unique TXXXX in CSV: 206
TXXXX.json files:     226

In [10]:
from pathlib import Path
import pandas as pd
import re

TRACK_SUMMARIES_DIR = Path("track_summaries")
CSV_PATH = "./debug/track_matches.csv"

# Load track IDs from CSV
df = pd.read_csv(CSV_PATH)
csv_track_ids = set(df["track_id"].astype(str))

# Get TXXXX.json files from folder
pattern = re.compile(r"^T\d{4}\.json$")

json_track_ids = {
    p.stem
    for p in TRACK_SUMMARIES_DIR.iterdir()
    if p.is_file() and pattern.match(p.name)
}

# Present in track_summaries, but absent from track_matches.csv
missing_from_csv = sorted(json_track_ids - csv_track_ids)

print(f"TXXXX.json files in track_summaries: {len(json_track_ids)}")
print(f"Unique TXXXX in track_matches.csv:   {len(csv_track_ids)}")
print(f"In track_summaries but NOT in CSV:   {len(missing_from_csv)}")
print()

for track_id in missing_from_csv:
    print(track_id)

TXXXX.json files in track_summaries: 226
Unique TXXXX in track_matches.csv:   206
In track_summaries but NOT in CSV:   20

T0023
T0039
T0040
T0044
T0050
T0105
T0111
T0119
T0133
T0138
T0166
T0167
T0171
T0201
T0205
T0207
T0214
T0215
T0224
T0225